### ISSUE TITLE
Music Dataset

### ISSUE THREAD

**Issue by dylanrandle** [capstone2019-neuralsearch/AC297r_2019_NAS#16]
Train DARTS with Music Dataset, try to get state-of-art

**Comment by JiaweiZhuang** [comment]
Do you mean https://github.com/mlachmish/MusicGenreClassification

**Comment by jlaasri** [comment]
It only has the original paper baseline, so it may not be worth using DARTS on it. Getting better results on a dataset that has been manually explored by many people would probably be more meaningful. Let's keep this one in mind if it can be useful to explore architecture transferring / sparsity comparison etc.
