### ISSUE TITLE
Is the graphene dataset link broken?

### ISSUE THREAD

**Issue by cow8** [capstone2019-neuralsearch/AC297r_2019_NAS#22]
the link https://capstone2019-google.s3.amazonaws.com/graphene_processed.nc returns 403 forbidden. Is there some technical problems or just withdraw the released dataset due to policy changes? It would be great if the dataset can be openly accessed, thanks! After all, it takes ~15,600 kWh to generate the data as shown in the milestone presentation: ) @JiaweiZhuang

**Comment by JiaweiZhuang** [comment]
Thanks for reporting, we will check what happens. In meantime you can simply pull the raw data by

```
wget https://github.com/phanakata/ML_for_kirigami_design/raw/master/mddata/15grid_shuffled.dat
```

and then run [this notebook](https://github.com/capstone2019-neuralsearch/AC297r_2019_NAS/blob/master/notebooks/data_exploration/graphene_kirigami/convert_rawdata_to_image.ipynb) to get the same file.

**Comment by cow8** [comment]
Tested from the US, Japan, and mainland China and all failed to fetch data

**Comment by cow8** [comment]
thanks for suuuuuuuuuuuuper fast response! I will try it!
