### ISSUE TITLE
Random search algorithm for comparison

### ISSUE THREAD

**Issue by dylanrandle** [capstone2019-neuralsearch/AC297r_2019_NAS#5]
Implement random search over the genotype object, such that we can use it for comparison

**Comment by JiaweiZhuang** [comment]
@jlaasri This discussion seems very useful: quark0/darts#3

**Comment by JiaweiZhuang** [comment]
Seems like a useful paper: [Random Search and Reproducibility for Neural Architecture Search](https://arxiv.org/abs/1902.07638)

**Comment by jlaasri** [comment]
See https://github.com/capstone2019-neuralsearch/darts/commit/ebe158ccd36dedc2ac69ba6153ddfdbbb274c894.

The script is still not totally general but it produces comparable genotypes to what we've produced so far.

**Comment by jlaasri** [comment]
See branch "random_search" of darts repo.

What we can do now:
` python random_search.py N --arg_example1 50 -arg_example2 300 ...`

This will run "train.py" N times with N different random cells. All the arguments after "N" are directly passed to "train.py". In practice, this code will run the following command N times:
`python train.py --random --arg_example1 50 -arg_example2 300 ...`.

Also, when running train.py, the genotype is saved to genotype.arch for easy access.

**Comment by jlaasri** [comment]
Done with random_search*.py
