### ISSUE TITLE
Refactor DARTS code to support non-square images

### ISSUE THREAD

**Issue by JiaweiZhuang** [capstone2019-neuralsearch/AC297r_2019_NAS#7]
The original DARTS implementation (https://github.com/quark0/darts) requires the input image to be a perfect `n*n` square. Otherwise it crashes as:

```
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 7 and 8 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111
```

This is fine for CIFAR (32x32) and MNIST (28x28), but most scientific images won't be a perfect square. The graphene data is 3x5 / 30x80 for example.

If the code is too hard to refactor, we can also resample all input images to a perfect square, which is less ideal.

**Comment by JiaweiZhuang** [comment]
Ideally there should be a [parameterized tests](https://docs.pytest.org/en/latest/parametrize.html) for the DARTS code to check all kinds of input shapes. This can be done more easily if the code runs on CPU (#8).

**Comment by JiaweiZhuang** [comment]
You should be able to run the test suite on GPU via #10.

**Comment by dylanrandle** [comment]
Solved via https://github.com/capstone2019-neuralsearch/darts/commit/c54e3b4b2b70eb572f2ca159fd9935f4716deb0c
